#!/usr/bin/env python3
"""
Model Converter & Updater for ESP32 Wake Word Detection
Reads a .tflite model file, extracts quantization parameters,
and generates main/model_data.h with an aligned C byte array.
"""

import sys
import os

def find_python_with_tflite():
    # If current environment has tensorflow, use it
    try:
        import tensorflow
        return sys.executable
    except ImportError:
        pass
    
    # Check virtual environments in sibling directories
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    parent_dir = os.path.dirname(project_root)
    
    candidate_venvs = [
        os.path.join(parent_dir, "esp32_wakeword_trainer", ".venv", "bin", "python"),
        os.path.join(parent_dir, ".venv", "bin", "python"),
    ]
    for candidate in candidate_venvs:
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return sys.executable

def main():
    # If current python lacks tensorflow, re-exec with venv python
    try:
        import tensorflow
    except ImportError:
        venv_py = find_python_with_tflite()
        if venv_py != sys.executable:
            os.execv(venv_py, [venv_py] + sys.argv)
        else:
            print("Error: TensorFlow is required to extract quantization parameters. Please run with 'uv run' or in a venv.")
            sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    parent_dir = os.path.dirname(project_root)
    
    default_model = os.path.join(parent_dir, "esp32_wakeword_trainer", "saved_model", "wakeword_quantized.tflite")
    tflite_path = sys.argv[1] if len(sys.argv) > 1 else default_model
    output_header = os.path.join(project_root, "main", "model_data.h")
    
    if not os.path.isfile(tflite_path):
        print(f"Error: Model file not found at '{tflite_path}'")
        sys.exit(1)
        
    print(f"Reading model: {tflite_path}")
    with open(tflite_path, "rb") as f:
        model_bytes = f.read()
    model_len = len(model_bytes)
    print(f"Model size: {model_len:,} bytes ({model_len / 1024:.2f} KB)")
    
    # Extract exact quantization parameters using tflite interpreter
    try:
        import tensorflow as tf
        interpreter = tf.lite.Interpreter(model_path=tflite_path)
        interpreter.allocate_tensors()
        in_details = interpreter.get_input_details()[0]
        out_details = interpreter.get_output_details()[0]
        
        in_scale, in_zero = in_details['quantization']
        out_scale, out_zero = out_details['quantization']
        in_shape = list(in_details['shape'])
        out_shape = list(out_details['shape'])

        if in_scale <= 0.0:
            raise ValueError(f"Model input is not quantized (scale is {in_scale})")

        print(f"Extracted Quantization Parameters:")
        print(f"  Input:  shape={in_shape}, scale={in_scale:.8f}, zero_point={in_zero}")
        print(f"  Output: shape={out_shape}, scale={out_scale:.8f}, zero_point={out_zero}")
    except Exception as e:
        print(f"\n[FATAL ERROR] Failed to extract quantization parameters from '{tflite_path}': {e}", file=sys.stderr)
        print("Update aborted. model_data.h was NOT modified to prevent corrupted deployments.", file=sys.stderr)
        sys.exit(1)
    
    print(f"Generating C header: {output_header}")
    os.makedirs(os.path.dirname(output_header), exist_ok=True)
    
    with open(output_header, "w") as f:
        f.write("/**\n")
        f.write(" * Automatically generated by update_model.py\n")
        f.write(f" * Source: {os.path.basename(tflite_path)} ({model_len} bytes)\n")
        f.write(" */\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <stddef.h>\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define MODEL_INPUT_SCALE      ({in_scale:.8f}f)\n")
        f.write(f"#define MODEL_INPUT_ZERO_POINT ({in_zero})\n")
        f.write(f"#define MODEL_OUTPUT_SCALE     ({out_scale:.8f}f)\n")
        f.write(f"#define MODEL_OUTPUT_ZERO_POINT ({out_zero})\n")
        f.write(f"#define MODEL_NUM_SLICES       ({in_shape[1] if len(in_shape) >= 2 else 49})\n")
        f.write(f"#define MODEL_NUM_FEATURES     ({in_shape[2] if len(in_shape) >= 3 else 40})\n")
        f.write(f"#define MODEL_NUM_CLASSES      ({out_shape[1] if len(out_shape) >= 2 else 2})\n\n")
        f.write(f"const size_t g_model_data_len = {model_len};\n\n")
        f.write("alignas(16) const unsigned char g_model_data[] = {\n")
        
        # Write bytes 12 per line
        bytes_per_line = 12
        for i in range(0, model_len, bytes_per_line):
            chunk = model_bytes[i:i+bytes_per_line]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            if i + bytes_per_line < model_len:
                f.write(f"  {hex_str},\n")
            else:
                f.write(f"  {hex_str}\n")
        f.write("};\n")
        
    print("Model header generated successfully!")

if __name__ == "__main__":
    main()
